// Auto-generated by scripts/generate-agent-docs-content.ts
// Run: bun scripts/generate-agent-docs-content.ts
// This file embeds all agent documentation markdown and index.json so it survives bundling.

export const BUILTIN_AGENT_DOCS_CONTENT: Record<string, string> = {
  "index.json": `{
  "version": 1,
  "label": "Geistr Agent Documentation",
  "navigation": [
    {
      "title": "Core Concepts",
      "items": [
        { "title": "Profile, Soul, and Identity", "path": "profile-and-soul.md" },
        { "title": "Memory System", "path": "memory.md" },
        { "title": "Session and Compaction", "path": "session-and-compaction.md" }
      ]
    },
    {
      "title": "Tools and Skills",
      "items": [
        { "title": "Tool Reference", "path": "tools-reference.md" },
        { "title": "Skills Guide", "path": "skills-guide.md" }
      ]
    },
    {
      "title": "Runtime and Safety",
      "items": [
        { "title": "Permissions and Access Modes", "path": "permissions.md" }
      ]
    },
    {
      "title": "External Integration",
      "items": [
        { "title": "MCP Server Integration", "path": "mcp.md" }
      ]
    },
    {
      "title": "Background Work",
      "items": [
        { "title": "Background Loops", "path": "loops.md" }
      ]
    }
  ]
}
`,
  "loops.md": `# Background Loops

This document explains the background loop system: what loops exist, how they work, and how to interact with them.

## What are background loops?

Background loops are reusable processes that run inside the app runtime. They handle maintenance and background work without blocking the chat.

Loops have:

- A **name** and **description** visible in the loop catalog
- A **lifecycle**: prepare → execute → validate → apply → finalize
- **Steps** that emit progress so the UI can show advancement
- A **result** stored as a hidden loop_result event
- Optional **needsAttention** flag if the loop encountered a problem

## Available loops

### session-compaction

- **Trigger**: Automatic when message token count exceeds the threshold (approx. 15,000 tokens)
- **Purpose**: Condenses older conversation into a plain text summary to keep the context window manageable
- **Result**: A summary event is saved; recent messages are retained in the window
- **needsAttention**: True only if compaction failed

### memory-indexing

- **Trigger**: Automatic after the database has at least 50 unindexed visible user/assistant messages across all non-deleted chats
- **Purpose**: Extracts high-signal durable facts from the conversation and stores them as memory items
- **Result**: New memories are created with links between related items
- **needsAttention**: True only if indexing failed

## How loops appear in the UI

- When a loop is running, the chat area shows a compact loop progress widget
- The widget shows: current step / total steps and a status label
- When the loop completes or fails, the widget clears
- Loop events are stored as hidden events — they are not visible chat messages

## Interacting with loops

There are two loop tools:

### loop_read (Safe)

- \`loop_read({ action: "list" })\` — see all available loops
- \`loop_read({ action: "status", runId: "..." })\` — check status of a loop run

### loop_write (Internal_mutate)

- \`loop_write({ action: "start", loopName: "session-compaction" })\` — start a loop manually
- \`loop_write({ action: "start", loopName: "session-compaction", input: { force: true } })\` — force compaction immediately

## Important rules

- Most loops run automatically. You rarely need to start them manually.
- Compaction runs on its own trigger (token count threshold).
- Memory indexing runs on its own trigger (unindexed message count).
- Only use loop_write when the user explicitly asks.
- If a loop fails, it sets needsAttention: true and the UI may show an indication.
- Loop results are stored as hidden events — do not treat them as visible chat messages.
- A queued run ID (queued_*) returned by loop_write is valid. Use it with loop_read status and it will resolve to the actual final run.
`,
  "mcp.md": `# MCP Server Integration

This document explains how MCP (Model Context Protocol) servers work in Geistr, how MCP tools are exposed, and how you should use them.

## What are MCP servers?

MCP servers are external programs or services that expose tools for the agent to use. They communicate via:

- **STDIO**: a local command that launches an MCP server process
- **Streamable HTTP**: a remote HTTP endpoint that speaks the MCP protocol

Users configure MCP servers through the MCP Servers screen in the sidebar.

## How MCP tools reach you

When a user adds and enables an MCP server:

1. The runtime starts/connects to the server
2. The server advertises its available tools
3. The runtime registers those tools with prefixed names: \`mcp.<serverName>.<toolName>\`
4. You see them in your tool catalog alongside Geistr's native tools

When the user disables or deletes a server, its tools are removed from your catalog.

## Rules for using MCP tools

- MCP tools are **external and untrusted**. They are not part of the Geistr core and may change or become unavailable.
- Use MCP tools only when relevant to the user's request. Do not call them speculatively.
- MCP tools are **permission-gated** just like any other tool. Their permission tier depends on what they do. When in doubt, the system is conservative.
- If an MCP tool requires approval, wait for the approval UI. Do not ask the user to approve in chat.
- Do not claim an MCP action succeeded unless the tool call returned success.
- MCP servers may fail or be unreachable. Handle connection errors gracefully and inform the user.
- Do not ask the user to paste secrets or API keys into chat for MCP setup — the MCP Servers UI has fields for this.

## Auth/credentials for MCP servers

Some MCP servers require authentication:

- **API keys / bearer tokens**: stored in the app's secure secret store. You never see raw secret values in your context.
- **OAuth**: set up through the MCP Servers UI with a browser-based authorization flow. Tokens are stored securely.
- **Environment variables**: STDIO MCP servers can receive env vars from the app process or from configured secret values.

If a server needs auth that isn't configured, it may return auth errors. Do not ask the user to configure secrets through chat.

## Graceful handling

- If an MCP tool is not available: "The X MCP tool is not available right now. The server may be disabled or disconnected."
- If an MCP tool returns an error: "The MCP tool returned an error. The issue may be temporary or the server may need reconfiguration."
- If no MCP servers are configured: "No MCP servers are configured. You can add one from the MCP Servers screen in the sidebar."
`,
  "memory.md": `# Memory System

This document explains how the Geistr memory system works: what memory is, how it gets created automatically, and when you should use explicit memory tools.

## Overview

Memory stores durable facts and context about the user and the world. It is separate from:

- **Profile** (identity, behavior, settings — use \`profile_write\`)
- **Session** (conversation transcript — managed automatically)
- **Session summary** (condensed history from compaction — automatic)

Memory is persisted in SQLite and lives across all sessions.

## Two ways memories are created

### 1. Automatic memory indexing (background)

After the database accumulates at least 50 unindexed visible user/assistant messages across all non-deleted chats, the automatic memory indexing loop runs in the background. It processes the oldest global batch, sending all available messages up to a 75-message cap. It:

1. Reads recent unindexed messages
2. Extracts high-signal context at the conversation level
3. Validates each candidate against the standard: "would a careful human save this as long-term memory?"
4. Creates memory items with type, importance, and tags
5. Links related memories together (up to 5 links per memory)

**You do not control automatic indexing.** It happens on its own. Do not try to trigger it or influence it through chat.

### 2. Explicit memory write (agent or user initiated)

When the user explicitly says something like:

- "Remember that my favorite color is blue"
- "Forget what I told you about X"
- "That memory is wrong, update it"
- "What do you know about X?"

Use the explicit memory tools:

- \`memory_write\` for create, update, delete, supersede, reinforce
- \`memory_read\` for search, list recent, get by ID

## When to use memory_write

Only use \`memory_write\` when the user explicitly asks you to remember, change, or delete something, or when the user's instruction clearly implies durable storage.

**Do not** use \`memory_write\` for:

- Changing your own name, identity, role, style, or behavior → use \`profile_write\` on assistantProfile
- Changing the user's display name, locale, or goals → use \`profile_write\` on userProfile
- Changing app settings like theme or permissions → use \`profile_write\` on appConfig
- Storing transient conversation context that won't matter next session → let the session handle it
- Screaming out about every minor preference you infer → let the background indexing loop handle automatic extraction
- Attempting to store skill instructions, tool definitions, or system configuration → these belong in files, not memory

## Memory_write actions

| Action | Purpose | When to use |
|--------|---------|-------------|
| \`create\` | Store a new durable fact | User says "remember X" |
| \`update\` | Change an existing memory | User says "that's not right, it's actually Y" |
| \`delete\` | Remove a memory permanently | User says "forget X" or "delete that" |
| \`supersede\` | Mark old memory as replaced by new | User corrects something you remembered; creates replacement with link to old |
| \`reinforce\` | Increase strength/importance of a memory | User confirms or repeats a fact |

## Memory_read actions

| Action | Purpose |
|--------|---------|
| \`search\` | Find memories by text query |
| \`list_recent\` | List recent active/cold memories |
| \`get\` | Get a single memory by ID, optionally with linked memories |

## Memory structure

Each memory has:

- **Content**: The stored fact or context
- **Type/category**: Preference, Profile, Goal, Fact, etc.
- **Status**: active, cold, deleted
- **Importance**: relative importance score
- **Stability**: how settled this memory is
- **Strength**: reinforcement count
- **Tags**: optional categorization tags
- **Source**: what session/message created it
- **Links**: up to 5 related memories

## Memory in the runtime prompt

When a session starts, the runtime retrieves relevant memories and injects them into the prompt under "Relevant long-term memory". This happens automatically.

Memory items in the prompt include:

- The category label (Preference, Profile, Goal, Fact)
- The content
- When it was created and last updated

This gives you durable context about the user without needing to search memory at the start of every session. If you need more context on a specific topic, use \`memory_read search\`.

## Important rules

- Do not silently add memory based only on inference during chat
- The background indexing loop handles automatic extraction — let it do its job
- Profile is source of truth over memory when they conflict
- If the user changes their display name in profile, do not keep an outdated memory about their name
- Supersede is preferred over delete+create for corrections because it preserves the history
- Memory content should be high-signal and human-valuable — the bar is "would a careful human save this?"
`,
  "permissions.md": `# Permissions and Access Modes

This document explains the permission system: the three access modes, what each mode allows, and how tool approval works.

## The three modes

The user can select the permission mode from a small icon beside the chat composer.

### 1. Read Only

In Read Only mode, you can read safe context but most mutations require approval.

| Action type | Behavior |
|-------------|----------|
| Read profile, memory, skills, loops | ✅ Allow automatically |
| Read files | ✅ Allow automatically |
| Update profile or memory | ❌ Requires approval |
| Write or edit files | ❌ Requires approval |
| Run shell commands | ❌ Requires approval |
| Network / internet access | ❌ Requires approval |
| Destructive commands (sudo, recursive rm) | 🚫 Blocked |

### 2. Default (recommended)

In Default mode, you can work freely inside the app boundary. Mutations outside the boundary or dangerous actions require approval.

| Action type | Behavior |
|-------------|----------|
| Read profile, memory, skills, loops | ✅ Allow automatically |
| Read files | ✅ Allow automatically |
| Update profile or memory (when user explicitly asks) | ✅ Allow automatically |
| Write or edit files inside allowed workspace | ✅ Allow automatically |
| Write or edit files outside workspace | ❌ Requires approval |
| Run safe shell commands | ✅ Allow automatically |
| Dangerous shell (package install, git push, network) | ❌ Requires approval |
| Internet / network access | ❌ Requires approval |
| Destructive commands | 🚫 Blocked |

### 3. Full Access

In Full Access mode, all normal actions proceed without approval prompts.

| Action type | Behavior |
|-------------|----------|
| All safe reads | ✅ Allow automatically |
| All profile/memory/file writes | ✅ Allow automatically |
| All shell commands (non-blocked) | ✅ Allow automatically |
| Network / internet access | ✅ Allow automatically |
| Destructive commands (sudo, forced recursive removal) | 🚫 Still blocked |

Full Access still blocks obviously catastrophic commands. It does not give blind trust for everything.

## How approval works

When a tool requires approval:

1. The runtime pauses the tool call
2. The app UI shows an approval card with:
   - Tool name
   - Action / command / path
   - Risk tier
   - Reason
   - Approve / Deny buttons
3. The user clicks Approve or Deny
4. If approved, the tool runs and returns its result to you
5. If denied, the tool returns an error that you should handle gracefully

**Important rules for you:**

- Do not ask the user to approve in chat as a substitute for the UI approval flow
- Do not claim a tool succeeded if it was denied
- Do not try to bypass approval by using a different tool for the same effect
- Handle denial gracefully: explain what was denied and why, suggest alternatives
- If a tool times out waiting for approval, it may return a timeout error — handle it naturally

## Blocked actions

Some actions are always blocked regardless of mode:

- \`sudo\` commands
- Recursive forced removal (\`rm -rf /\`, \`rm -rf /*\`)
- Filesystem formatting (\`mkfs\`, \`dd\` to block devices)
- Any command that could destroy the system or user data

These cannot be approved by the user. If you try one, it will return an error. Do not suggest blocked commands.

## Permission tiers reference

| Tier | Description | Examples |
|------|-------------|---------|
| Safe | Read-only, no risk | profile_read, memory_read, skill_load, loop_read, reading files |
| Internal_mutate | Modifies internal app state | profile_write, memory_write, loop_write |
| Workspace_mutate | Creates or changes files | file_write, file_edit, safe shell mutations |
| Dangerous | Network, package changes, git mutations | curl, wget, npm install, git push, ssh |
| Blocked | System-destructive | sudo, recursive forced rm, mkfs, dd |
`,
  "profile-and-soul.md": `# Profile, Soul, and Identity

This document explains the profile and identity system in Geistr. It covers what profiles are, how the Soul works, and when to use profile tools versus memory tools or other systems.

## Overview

Geistr has two profiles:

1. **User profile** — represents the human using the app
2. **Assistant profile** — represents the AI assistant (you)

Both are stored persistently in SQLite and can be read or updated with profile tools.

There is also a **session** which is a conversation transcript. Sessions are managed separately and are not profiles.

## Profile vs Memory vs Session

This is the most important distinction in the system:

| System | Purpose | Tool | Persistence |
|--------|---------|------|-------------|
| Profile | Identity, behavior, preferences, config | \`profile_read\`, \`profile_write\` | Permanent until changed |
| Memory | Durable facts about the user and world | \`memory_read\`, \`memory_write\` | Permanent until deleted/superseded |
| Session | Conversation transcript | No direct user tool | Per-chat, persist until deleted |
| Compaction summary | Condensed session history | Automatic | Hidden metadata |

**Rule of thumb:**

- If it's about **who the assistant is** (name, role, tone, style, boundaries, Soul) → **profile_write** on assistantProfile
- If it's about **who the user is** (display name, locale, goals, preferences, constraints) → **profile_write** on userProfile
- If it's about **durable facts** the user wants remembered (project preferences, life context, important dates) → **memory_write**
- If it's about **how the app behaves** (theme, permissions mode, compaction settings) → **profile_write** on appConfig

## The Soul System

The Soul is the deepest identity layer of the assistant. It is stored in \`assistantProfile.soulPrompt\`.

Soul is different from other profile fields:

- **Soul**: The core identity — who you fundamentally are. Changes rarely and with care. Examples: "a calm, thoughtful personal assistant", "a patient tutor who explains concepts from first principles".
- **Persona summary**: A short label for the current persona.
- **Role prompt**: What you do — your job description. Can be updated more freely than Soul.
- **Style prompt / tone / communication style**: How you sound — your voice. Can be updated freely.
- **Boundary prompt**: What you should not do. Important for safety.
- **Memory prompt**: Guidance on what to remember or not remember. Important memory-related constraints.

### When to update which field

- User says "your name is X" → update \`assistantProfile.assistantName\` via profile_write
- User says "you are a tutor now" → update \`assistantProfile.rolePrompt\` or \`assistantProfile.personaSummary\`
- User says "be more concise" or "use more emojis" → update \`assistantProfile.stylePrompt\`, \`assistantProfile.tone\`, or \`assistantProfile.communicationStyle\`
- User says "never mention X" → update \`assistantProfile.boundaryPrompt\`
- User gives deep identity guidance → update \`assistantProfile.soulPrompt\`
- User says "remember that I prefer dark mode" → use **memory_write**, not profile
- User says "my display name is X" → update \`userProfile.displayName\`

## Profile fields reference

### Assistant profile

| Field | Type | Purpose |
|-------|------|---------|
| \`assistantName\` | string | Your name |
| \`soulPrompt\` | string (JSON) | Deep identity definition |
| \`personaSummary\` | string | Short persona label |
| \`rolePrompt\` | string (JSON) | Detailed role/behavior |
| \`stylePrompt\` | string (JSON) | Communication style |
| \`tone\` | string | Tone description |
| \`communicationStyle\` | string | Style description |
| \`boundaryPrompt\` | string (JSON) | Boundaries/limits |
| \`memoryPrompt\` | string (JSON) | Memory guidance |
| \`agentBehaviorNotesJson\` | string (JSON array) | Notes about behavior |

### User profile

| Field | Type | Purpose |
|-------|------|---------|
| \`displayName\` | string | Name to call the user |
| \`locale\` | string | Locale code (e.g. en-US) |
| \`languagePreferences\` | string | Language preferences |
| \`learningStyle\` | string | Learning style |
| \`goalsJson\` | string (JSON array) | User's goals |
| \`constraintsJson\` | string (JSON array) | User's constraints |
| \`additionalContextJson\` | string (JSON array) | Extra context |

## Profile is source of truth

Profile values always override session summaries and memory when they conflict.

For example:
- If a session summary says "the assistant has no fixed name" but \`assistantProfile.assistantName\` is "Hamoudi" → **the profile is correct**
- If a memory says "user prefers to be called X" but \`userProfile.displayName\` is "Y" → **the profile is correct**

Do not treat stale session summaries or outdated memories as authoritative over profile fields. If you notice a conflict, respect the profile.

## Important rules

- Never store assistant identity, personality, role, style, or behavior changes as memory — they belong in the profile
- Never use memory to change your own behavior or the user's display name
- Use \`profile_write\` for identity, name, soul, role, style, boundaries, and memory guidance changes
- Use \`memory_write\` for durable non-profile user context ("remember X")
- Always verify that \`profile_write\` returned success with expected changedFields before confirming the change to the user
`,
  "session-and-compaction.md": `# Session and Compaction

This document explains how sessions work, what compaction is, and how it affects your context window.

## Sessions

A session is a conversation transcript. It persists in SQLite under the user data directory.

Key facts about sessions:

- Every chat you have belongs to a session
- Sessions persist across app restarts
- Sessions have a unique key and are listed in the sidebar
- The runtime loads the most recent messages into your context window
- Sessions store: messages, profile snapshots, compaction summaries, and metadata events

## The context window limit

Your context window has a practical limit. As a session grows longer, the runtime needs to keep your context manageable. It does this through compaction.

## Compaction

Compaction is an automatic background loop that:

1. Triggers when the estimated token count of visible messages reaches the threshold (default: approximately 15,000 tokens)
2. Condenses the older portion of the conversation into a plain text summary
3. Saves the summary as a hidden event in the session
4. Retains only the most recent visible messages in the window
5. The summary plus recent messages become the ongoing context

### What compaction means for you

After compaction, your context will contain:

- The session summary (condensed history)
- Recent raw visible messages
- Profile data
- Relevant memories

The session summary is a continuity device. It tells you what happened earlier in the conversation so you don't lose context. But it is:

- **A summary, not a transcript** — details may be compressed or omitted
- **Potentially stale** — profile changes that happened after the summary was written may not be reflected in it
- **Not authoritative over profile** — if the summary says something that conflicts with the current profile, the profile wins

### Manual compaction

The user can also manually trigger compaction with:

- \`/compact\` — suggests a compact action
- \`/compact!\` — forces immediate compaction

These are user-initiated. You do not need to suggest or manage them.

### Your role in compaction

- You do not need to think about or manage compaction
- Compaction is an invisible system process
- If the user asks about compaction, you can explain it using this document
- If you notice context gaps from compaction, acknowledge them naturally

## Session summary vs memory

| Aspect | Session Summary | Memory |
|--------|----------------|--------|
| Scope | Current conversation only | Cross-session durable facts |
| Created by | Compaction loop (automatic) | Indexing loop (automatic) or explicit memory_write |
| Purpose | Continuity within a session | Long-term context across sessions |
| Stale risk | Yes, not updated until next compaction | Updated by indexing or explicit write |
| Conflict with profile | Profile wins | Profile wins |

## Multiple sessions

Users can have multiple sessions. Each session has its own transcript and compaction state. When switching sessions:

- The new session's context is loaded from scratch
- Session summaries from other sessions are not mixed in
- Memories are shared across all sessions

If the user asks about something from another session, use \`memory_read\` to find relevant memories, or ask the user for context.
`,
  "skills-guide.md": `# Skills Guide

This document explains what skills are, how to load and use them, and how to create, update, and delete them.

## What is a skill?

A skill is a structured markdown file that provides repeatable workflow instructions for a specific task. Skills exist to make your behavior predictable — following the same process every time for a given task.

Skills live in \`SKILL.md\` files, optionally with sibling reference files like \`GLOSSARY.md\`.

## Where skills live

There are two skill roots:

### Built-in skills

Bundled with the core package. Read-only. Example:

- \`writing-great-skills\`: Reference for writing and editing skills well

Built-in skills are always available but you cannot modify them through file tools.

### User-installed skills

Located in the user skills directory:

\`\`\`
C:\\Users\\moham\\AppData\\Roaming\\@geistr\\desktop\\skills\\<skill-name>\\SKILL.md
\`\`\`

User skills are editable. You can create, update, or delete them using normal file tools and shell commands.

## How to use a skill

1. Check the active skills catalog in your system prompt. It lists skills by name and short description.
2. If a task matches an installed skill, use \`skill_load({ name: "..." })\` to load the full instructions.
3. Follow the skill's instructions for the current turn/task.

**Important:** Do not act on a task that has a matching skill without loading it first. The skill contains mandatory workflow instructions.

## How to create a skill (when the user asks)

1. Ask the user what the skill should do
2. Use \`skill_load("writing-great-skills")\` to load the skill authoring reference — it explains how to write good skills
3. Create the skill folder and files using file tools:

\`\`\`
mkdir -p <user-skills-dir>/<skill-name>
write <user-skills-dir>/<skill-name>/SKILL.md
\`\`\`

4. The skill should include:
   - YAML frontmatter with name and description
   - Clear instructions/steps
   - Completion criteria
   - References if needed

5. Confirm the skill was created and is now available

## How to update a skill (when the user asks)

Use normal file read/edit/write tools on the skill's \`SKILL.md\` and any reference files.

## How to delete a skill (when the user asks)

Use normal file tools or shell commands to remove the skill folder.

## Important rules

- \`skill_load\` is read-only. It does not create, edit, or delete skills.
- To create, update, or delete skills, use normal file tools/commands under the user skills directory — subject to permission approval.
- Only create, update, or delete skills when the user explicitly requests it.
- Do not silently rewrite skills just because you think they could be improved.
- Loaded skill instructions apply for the current turn/task. Do not permanently inject them into every prompt.
- Do not use memory or profile tools to store skill instructions.
- Skill content is operational instruction, not long-term memory or profile data.
- If a skill references a glossary or other sibling file, \`skill_load\` with \`includeReferences: true\` will load it too.
`,
  "tools-reference.md": `# Tool Reference

This document is a complete reference for every custom tool available to you in Geistr. It covers purpose, inputs, outputs, permission tiers, and usage patterns.

## General principles

- Use the cheapest correct tool path for any task
- Every tool has a permission tier — some may require user approval depending on the current permission mode
- If a tool requires approval, wait for the app's approval UI; do not ask the user to approve in chat
- Do not claim success unless the tool returned success
- Always handle error responses gracefully

---

## profile_read

**Permission tier:** Safe (never requires approval)

Read the user profile, assistant profile, or app config.

### Actions

| Action | Returns | Use case |
|--------|---------|----------|
| \`userProfile\` | Display name, locale, goals, constraints, etc. | User asks "what do you know about me?" |
| \`assistantProfile\` | Assistant name, soul, role, style, boundaries, memory guidance | User asks "who are you?" or wants to check current settings |
| \`appConfig\` | App preferences: theme, permissions mode, compaction, provider, model | User asks about app settings |
| \`all\` | All profiles at once | Broader context needs |

### Example

\`\`\`
profile_read({ action: "assistantProfile" })
\`\`\`

---

## profile_write

**Permission tier:** Internal_mutate (requires user intent; may auto-approve in Default/Full Access)

Write to the user profile, assistant profile, or app config.

### Actions

| Action | Effect |
|--------|--------|
| \`userProfile\` | Updates user fields: displayName, locale, goals, constraints, etc. |
| \`assistantProfile\` | Updates assistant fields: assistantName, soulPrompt, rolePrompt, stylePrompt, tone, boundaryPrompt, memoryPrompt, etc. |
| \`appConfig\` | Updates app config: theme, permissions.mode, etc. |

### Usage rules

- Only use when the user explicitly asks to change something
- Never silently change your own profile or the user's profile
- Soul changes should be rare and deliberate
- Verify the returned \`changedFields\` to confirm the update worked
- Do not use for durable facts — use \`memory_write\` for "remember X"

### Example

\`\`\`
profile_write({
  action: "assistantProfile",
  assistantName: "Hamoudi",
  rolePrompt: "A patient coding tutor"
})
\`\`\`

---

## memory_read

**Permission tier:** Safe (never requires approval)

Search and retrieve durable memories.

### Actions

| Action | Parameters | Returns |
|--------|-----------|---------|
| \`search\` | \`{ query: string }\` | Matching memories with content, type, tags |
| \`list_recent\` | \`{ limit?: number }\` | Recent active/cold memories |
| \`get\` | \`{ memoryId: string, includeLinks?: boolean }\` | Single memory with optional linked memories |

### Usage rules

- Use when the user asks "what do you know about X?"
- Use when you need context that isn't in the prompt memory section
- Use before contradicting something you remember - verify the memory first

### Example

\`\`\`
memory_read({ action: "search", query: "Mohammed preferences" })
memory_read({ action: "get", memoryId: "mem_abc123", includeLinks: true })
\`\`\`

---

## memory_write

**Permission tier:** Internal_mutate (requires user intent; may auto-approve in Default/Full Access)

Create, update, delete, supersede, or reinforce memories.

### Actions

| Action | Parameters | Use case |
|--------|-----------|----------|
| \`create\` | \`{ content, type?, tags? }\` | User says "remember X" |
| \`update\` | \`{ memoryId, content?, tags? }\` | User corrects a memory |
| \`delete\` | \`{ memoryId }\` | User says "forget X" |
| \`supersede\` | \`{ memoryId, content?, tags? }\` | Replace old memory with corrected version while keeping history |
| \`reinforce\` | \`{ memoryId }\` | User confirms/repeats a fact, increasing its strength |

### Usage rules

- Only use when the user explicitly asks
- Do not silently add memories based on inference
- Do not use for identity/behavior changes — use \`profile_write\`
- Prefer \`supersede\` over \`delete\` + \`create\` for corrections
- Confirm with the user after creating important memories

### Example

\`\`\`
memory_write({ action: "create", content: "Mohammed prefers dark mode." })
memory_write({ action: "supersede", memoryId: "mem_old", content: "Mohammed uses light mode during daytime." })
\`\`\`

---

## skill_load

**Permission tier:** Safe (never requires approval)

Load full instructions for an installed skill.

### Input

\`\`\`
skill_load({ name: string, includeReferences?: boolean })
\`\`\`

- \`name\`: the skill name (e.g., "writing-great-skills")
- \`includeReferences\`: whether to include sibling files like GLOSSARY.md (default: true)

### Output

Returns structured content:

\`\`\`
{
  name: string;
  description: string | null;
  source: "builtin" | "user" | "workspace";
  files: [{ path: string; content: string }]
}
\`\`\`

### Usage rules

- If a matching skill appears in the active skills catalog, load it before acting
- Loaded skill instructions apply for the current turn/task
- Do not permanently inject skill text into every prompt
- Do not use memory to store skill instructions
- Do not use profile_write to store skill instructions

### Example

\`\`\`
skill_load({ name: "writing-great-skills" })
\`\`\`

---

## loop_read

**Permission tier:** Safe (never requires approval)

Read information about available loops and their status.

### Actions

| Action | Returns |
|--------|---------|
| \`list\` | All available loops with name and description |
| \`status\` | Status of a specific loop by run ID or queued ID |

### Example

\`\`\`
loop_read({ action: "list" })
loop_read({ action: "status", runId: "queued_..." })
\`\`\`

---

## loop_write

**Permission tier:** Internal_mutate (may require approval depending on loop type)

Start a background loop run.

### Actions

| Action | Parameters | Returns |
|--------|-----------|---------|
| \`start\` | \`{ loopName, input?: Record<string, unknown> }\` | run ID (may be queued_* if serialized) |

### Usage rules

- Only use when the user explicitly asks
- Most loops run automatically; you rarely need to start them manually
- Compaction and memory indexing run on their own triggers
- A queued run ID (queued_*) can be used with loop_read status and will resolve to the actual final run

### Example

\`\`\`
loop_write({ action: "start", loopName: "session-compaction" })
loop_write({ action: "start", loopName: "session-compaction", input: { force: true } })
\`\`\`

---

## File tools (read / write / edit / shell)

**Permission tiers:**

| Action | Tier |
|--------|------|
| Read files | Safe |
| Write new files | Workspace_mutate |
| Edit existing files | Workspace_mutate |
| Shell commands (safe) | Safe |
| Shell commands (mutate) | Workspace_mutate or Dangerous |

File tools are governed by the app's permission system. Safe reads never require approval. Mutations may require approval depending on the current mode (Read only / Default / Full access).

Your prompt will also include rules about when to ask before writing files. Follow those rules.

---

## MCP tools

MCP tools come from user-configured external servers. They are proxied through the runtime and follow the same permission system.

MCP tools have names like \`mcp.<serverName>.<toolName>\`.

Key rules:

- MCP tools are external and untrusted
- Permission classification is conservative — unknown MCP actions may require approval
- Do not ask the user to paste secrets into chat for MCP setup
- If an MCP action requires approval, wait for the app approval UI
- Do not claim an MCP action succeeded unless the tool returned success

---

## Permission tier summary

| Tier | Tools | Needs approval in Read only | Needs approval in Default | Needs approval in Full access |
|------|-------|---------------------------|--------------------------|------------------------------|
| Safe | profile_read, memory_read, skill_load, loop_read, safe shell/file reads | No | No | No |
| Internal_mutate | profile_write, memory_write, loop_write | Yes | No (if user intent is clear) | No |
| Workspace_mutate | file_write, file_edit, mutate shell commands | Yes | Only if outside workspace or dangerous | No |
| Dangerous | network commands, package installs, git mutation, dangerous shell | Yes | Yes | No |
| Blocked | sudo, recursive rm -rf, destructive system commands | Blocked | Blocked | Blocked |
`
};
