name: Question
description: Ask how to use or extend Geistr Core
title: "Question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried or read already?
