import { readFileSync, readdirSync, statSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const docsDir = join(import.meta.dirname, "..", "packages", "core", "src", "agent-docs");
const outputFile = join(import.meta.dirname, "..", "packages", "core", "src", "builtin-agent-docs-content.ts");

if (!existsSync(docsDir)) {
  console.error(`agent-docs directory not found at ${docsDir}`);
  process.exit(1);
}

const files = readdirSync(docsDir).filter(
  (f) => (f.endsWith(".md") || f === "index.json") && statSync(join(docsDir, f)).isFile()
);

const entries: string[] = [];

for (const file of files) {
  const content = readFileSync(join(docsDir, file), "utf-8");
  // Escape backticks and template literals
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");
  entries.push(`  "${file}": \`${escaped}\``);
}

const output = `// Auto-generated by scripts/generate-agent-docs-content.ts
// Run: bun scripts/generate-agent-docs-content.ts
// This file embeds all agent documentation markdown and index.json so it survives bundling.

export const BUILTIN_AGENT_DOCS_CONTENT: Record<string, string> = {\n${entries.join(",\n")}\n};\n`;

writeFileSync(outputFile, output, "utf-8");
console.log(`Generated ${outputFile} with ${files.length} files.`);
